### ISSUE TITLE
'Arithmetic operation resulted in an overflow.' in mhw.cs line 56

### ISSUE THREAD

**Issue by BoxOfCereal** [danong/mhw-dps-overlay#11]
I've not really used github before, please forgive any breach of etiquette.  It builds and hangs when run. When debugging this is the error message I'm getting.

**Comment by danong** [comment]
I believe this error is caused by building in x84 instead of x64. [Here's the docs for configuring VS to build x64](https://docs.microsoft.com/en-us/visualstudio/ide/how-to-configure-projects-to-target-platforms?view=vs-2017).

**Comment by BoxOfCereal** [comment]
Thank you very much! I'm really new to VS and would have never figured this out.
